/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "tests.check" instead.
 */

#include <check.h>

#include <stdio.h>
#include <string.h>
#include "s21_string.h"
#include "s21_sprintf.h"



char a[] = "Hello world";
char b[] = "Hello world\n\0";
char c[] = "a\n\0";
char d[] = " \n\0";
char e[] = " \0";
char f[] = "\n\0";
char g[] = "\0";



START_TEST(test_s21_strerror)
{
#ifdef __APPLE__
for (int i = 0; i != 108; i++) {
  ck_assert_str_eq(strerror(i), s21_strerror(i));
}
#elif __linux__
for (int i = 0; i != 134; i++) {
  ck_assert_str_eq(strerror(i), s21_strerror(i));
}
#endif



}
END_TEST

START_TEST(test_s21_strlen)
{
ck_assert_int_eq(s21_strlen("checkyourself"), strlen("checkyourself"));
ck_assert_int_eq(s21_strlen("23423423623432432"), strlen("23423423623432432"));
ck_assert_int_eq(s21_strlen("werfewfwefewf we3r2rf 23r 23r 32r wef23r23432rfewfwefwqwe"),
             strlen("werfewfwefewf we3r2rf 23r 23r 32r wef23r23432rfewfwefwqwe"));
ck_assert_int_eq(s21_strlen("wepofjewfw/wefw/320\0"), strlen("wepofjewfw/wefw/320\0"));
ck_assert_int_eq(s21_strlen("proverka_\nna_...>>>123>>.<123"), strlen("proverka_\nna_...>>>123>>.<123"));
ck_assert_int_eq(s21_strlen(""), strlen(""));
ck_assert_int_eq(s21_strlen("\0"), strlen("\0"));




}
END_TEST

START_TEST(test_s21_strpbrk)
{
ck_assert_pstr_eq(s21_strpbrk("", "zzp["),
                      strpbrk("", "zzp["));
ck_assert_pstr_eq(s21_strpbrk("proverka zaop", "a"),
                      strpbrk("proverka zaop", "a"));
ck_assert_pstr_eq(s21_strpbrk("proverka zaop", "p"),
                      strpbrk("proverka zaop", "p"));
ck_assert_pstr_eq(s21_strpbrk("qqqqqqqqqqqq", "q"),
                      strpbrk("qqqqqqqqqqqq", "q"));
ck_assert_pstr_eq(s21_strpbrk("qqqqqqqqqqqq", "\0"),
                      strpbrk("qqqqqqqqqqqq", "\0"));



}
END_TEST

START_TEST(test_s21_strrchr)
{
ck_assert_pstr_eq(s21_strrchr("proverka zaop", 'o'),
                      strrchr("proverka zaop", 'o'));
ck_assert_pstr_eq(s21_strrchr("looopa", ' '),
                      strrchr("looopa", ' '));
ck_assert_pstr_eq(s21_strrchr("", 'z'),
                      strrchr("", 'z'));
ck_assert_pstr_eq(s21_strrchr("proverka zaop", 'a'),
                      strrchr("proverka zaop", 'a'));
ck_assert_pstr_eq(s21_strrchr("proverka zaop", 'p'),
                      strrchr("proverka zaop", 'p'));
ck_assert_pstr_eq(s21_strrchr("qqqqqqqqqqqq", 'q'),
                      strrchr("qqqqqqqqqqqq", 'q'));
ck_assert_pstr_eq(s21_strrchr("qqqqqqqqqqqq", '\0'),
                      strrchr("qqqqqqqqqqqq", '\0'));
ck_assert_pstr_eq(s21_strrchr("qqqqqqqQqqqq", 'Q'),
                      strrchr("qqqqqqqQqqqq", 'Q'));



}
END_TEST

START_TEST(test_s21_strstr)
{
ck_assert_str_eq(strstr(a, "llo"), s21_strstr(a, "llo"));
ck_assert(s21_strstr(a, "word") == NULL);
ck_assert(s21_strstr(a, "\n") == NULL);
ck_assert_pstr_eq(strstr(e, "abc"), s21_strstr(e, "abc"));
ck_assert_ptr_eq(strstr(a, ""), s21_strstr(a, ""));


}
END_TEST

START_TEST(test_s21_strtok_1)
{
char str1[] = ",,,,,,Hello, world, how are you";
char str2[] = ",,,,,,Hello, world, how are you";

char delim[] = ",?";

ck_assert_str_eq(s21_strtok(str1, delim), strtok(str2, delim));
ck_assert_str_eq(s21_strtok(S21_NULL, delim), strtok(S21_NULL, delim));
ck_assert_str_eq(s21_strtok(S21_NULL, delim), strtok(S21_NULL, delim));



}
END_TEST

START_TEST(test_s21_strtok_2)
{
char test1[50] = "aboba,hello,world,trim";
  char test2[50] = "aboba,hello,world,trim";
  char delim1[10] = "123,";
  char *orig1 = {0}, *copy1 = {0};
  orig1 = strtok(test1, delim1);
  copy1 = s21_strtok(test2, delim1);
  char orig_res1[1000] = {0};
  char copy_res1[1000] = {0};
  while (orig1 != NULL) {
    strcat(orig_res1, orig1);
    orig1 = strtok(NULL, delim1);
  }
  while (copy1 != NULL) {
    strcat(copy_res1, copy1);
    copy1 = s21_strtok(NULL, delim1);
  }
  ck_assert_str_eq(orig_res1, copy_res1);

  char str[] = "School-21";
  char *tok1 = s21_strtok(str, "-");
  char *tok2 = strtok(str, "-");
  char *tok3 = s21_strtok(str, "");
  char *tok4 = strtok(str, "");
  char *tok5 = s21_strtok(str, "oo");
  char *tok6 = strtok(str, "oo");
  char *tok7 = s21_strtok(str, "Sc");
  char *tok8 = strtok(str, "Sc");
  char *tok9 = s21_strtok(str, "21");
  char *tok10 = strtok(str, "21");

  ck_assert_msg(!strcmp(tok1, tok2), "1st strtok test failed");
  ck_assert_msg(!strcmp(tok3, tok4), "2nd strtok test failed");
  ck_assert_msg(!strcmp(tok5, tok6), "3rd strtok test failed");
  ck_assert_msg(!strcmp(tok7, tok8), "4rth strtok test failed");
  ck_assert_msg(!strcmp(tok9, tok10), "5th strtok test failed");





}
END_TEST

START_TEST(test_s21_memchr)
{
ck_assert_ptr_eq(memchr(a, 'e', 4), s21_memchr(a, 'e', 4));
ck_assert_ptr_eq(memchr(a, 'd', 4), s21_memchr(a, 'd', 4));
ck_assert_ptr_eq(memchr(e, 'd', 1), s21_memchr(e, 'd', 1));
char *s1 = "This is a s21_memchr test";
ck_assert_ptr_eq(s21_memchr(s1, 's', 0), memchr(s1, 's', 0));
ck_assert_ptr_eq(s21_memchr(s1, 's', 2), memchr(s1, 's', 2));
ck_assert_ptr_eq(s21_memchr(s1, 's', 20), memchr(s1, 's', 20));
ck_assert_ptr_eq(s21_memchr(s1, 'u', 20), memchr(s1, 'u', 20));
ck_assert_ptr_eq(s21_memchr(s1, 'u', 25), memchr(s1, 'u', 25));



}
END_TEST

START_TEST(test_s21_memcmp)
{
ck_assert(memcmp(a, a, 10) == s21_memcmp(a, a, 10));
ck_assert(s21_memcmp(a, c, 3) < 0);
ck_assert(s21_memcmp(c, a, 3) > 0);
char *s1 = "This is a 1st string s21_memcmp test";
char *s2 = "This is a 2nd string s21_memcmp test";
ck_assert_msg(s21_memcmp(s1, s2, 36) == memcmp(s1, s2, 36),
              "1st memcmp test failed.");
ck_assert_msg(s21_memcmp(s1, s2, 2) == memcmp(s1, s2, 2),
              "2nd memcmp test failed.");
ck_assert_msg(s21_memcmp(s1, s2, 0) == memcmp(s1, s2, 0),
              "3rd memcmp test failed.");



}
END_TEST

START_TEST(s21_memcmp_different_string_but_same_comparable_bytes)
{
char string_1[] = "1234";
char string_2[] = "1235";
ck_assert_int_eq(memcmp(string_1, string_2, 3),
                 s21_memcmp(string_1, string_2, 3));

}
END_TEST

START_TEST(s21_memcmp_first_string_bigger)
{
char string_1[] = "4321";
char string_2[] = "1235";
ck_assert_int_gt(s21_memcmp(string_1, string_2, 10), 0);


}
END_TEST

START_TEST(s21_memcmp_second_string_bigger)
{
char string_1[] = "1235";
char string_2[] = "4321";
ck_assert_int_lt(s21_memcmp(string_1, string_2, 10), 0);

}
END_TEST

START_TEST(s21_memcmp_empty_strings)
{
char string_1[] = "";
char string_2[] = "";
ck_assert_int_eq(memcmp(string_1, string_2, 1),
                 s21_memcmp(string_1, string_2, 1));

}
END_TEST

START_TEST(s21_memcmp_different_string_compare_null_bytes)
{
char string_1[] = "4321";
char string_2[] = "1234";
ck_assert_int_eq(memcmp(string_1, string_2, 0),
                 s21_memcmp(string_1, string_2, 0));






/////////////// Gar


}
END_TEST

START_TEST(S21_MEMCPY)
{
char b1[50] = {0};
char b2[50] = {0};
ck_assert_str_eq(memcpy(b1, a, 5), s21_memcpy(b2, a, 5));
ck_assert_str_eq(memcpy(b1, e, 1), s21_memcpy(b2, e, 1));
char *src1 = "schesrdsfdsfdsfesr";
int len = s21_strlen(src1);
char dest1[100] = {0};
char dest2[100] = {0};
char dest3[100] = {0};
char dest4[100] = {0};
char dest5[100] = {0};
char dest6[100] = {0};
char dest7[100] = {0};
char dest8[100] = {0};
char dest9[100] = {0};
char dest10[100] = {0};
s21_memcpy(dest1, src1, len + 1);
memcpy(dest2, src1, len + 1);
s21_memcpy(dest3, src1, 5);
memcpy(dest4, src1, 5);
s21_memcpy(dest5, src1, 0);
memcpy(dest6, src1, 0);
s21_memcpy(dest7, src1, 18);
memcpy(dest8, src1, 18);
s21_memcpy(dest9, src1, 1);
memcpy(dest10, src1, 1);
ck_assert_str_eq(dest1, dest2);
ck_assert_str_eq(dest3, dest4);
ck_assert_str_eq(dest5, dest6);
ck_assert_str_eq(dest7, dest8);
ck_assert_str_eq(dest9, dest10);

}
END_TEST

START_TEST(S21_MEMSET)
{
char b1[50] = "lolkek";
char b2[50] = "lolkek";
ck_assert_str_eq(memset(b1, '*', 8), s21_memset(b2, '*', 8));
ck_assert_str_eq(memset(b1, '#', 3), s21_memset(b2, '#', 3));
ck_assert_str_eq(memset(b1, '|', 1), s21_memset(b2, '|', 1));

}
END_TEST

START_TEST(S21_STRNCAT)
{
char b1[20] = "a";
char b2[20] = "a";
char b3[50] = "lolkek";
char b4[50] = "lolkek";
ck_assert_str_eq(strncat(b1, a, 5), s21_strncat(b2, a, 5));
ck_assert_str_eq(strncat(b3, "cheburek", 9), s21_strncat(b4, "cheburek", 9));

}
END_TEST

START_TEST(S21_STRCHR)
{
ck_assert_str_eq(strchr(a, 'l'), s21_strchr(a, 'l'));
ck_assert(s21_strchr(a, 'n') == NULL);
ck_assert(s21_strchr(a, '\n') == NULL);
ck_assert_str_eq(strchr(a, '\0'), s21_strchr(a, '\0'));
ck_assert_str_eq(strchr(g, '\0'), s21_strchr(g, '\0'));
ck_assert_str_eq(strchr(e, ' '), s21_strchr(e, ' '));

}
END_TEST

START_TEST(S21_STRNCMP)
{
ck_assert(s21_strncmp(a, a, 10) == 0);
ck_assert(s21_strncmp(a, c, 3) < 0);
ck_assert(s21_strncmp(c, a, 3) > 0);
ck_assert(s21_strncmp(f, g, 1) > 0);

}
END_TEST

START_TEST(S21_STRNCPY)
{
char b1[60] = "lolkek";
char b2[60] = "lolkek";
ck_assert_pstr_eq(strncpy(b1, a, 3), s21_strncpy(b2, a, 3));
ck_assert_pstr_eq(strncpy(b1, b, 10), s21_strncpy(b2, b, 10));
ck_assert_pstr_eq(strncpy(b1, c, 8), s21_strncpy(b2, c, 8));

}
END_TEST

START_TEST(S21_STRCSPN)
{
ck_assert_int_eq(strcspn(a, "Hel"), s21_strcspn(a, "Hel"));
ck_assert_int_eq(strcspn(a, "llo"), s21_strcspn(a, "llo"));
ck_assert_int_eq(strcspn(a, a), s21_strcspn(a, a));
ck_assert_int_eq(strcspn(a, e), s21_strcspn(a, e));




//////////// Gar




    

///////////////

}
END_TEST

START_TEST(test_s21_sprintf_d)
{
char c1[100] = "a";
char c2[100] = "a";
char c3[100] = "lolkek";
char c4[100] = "lolkek";
ck_assert_int_eq(sprintf(c1, "test %d%d%d", 5, 6, 10),
                 s21_sprintf(c2, "test %d%d%d", 5, 6, 10));
ck_assert_str_eq(c1, c2);
ck_assert_int_eq(sprintf(c3 + 6, "%d", -6000),
                 s21_sprintf(c4 + 6, "%d", -6000));
ck_assert_str_eq(c3, c4);
ck_assert_int_eq(sprintf(c1, "%10d %-10d %4.10d", 1, 666, 2544325),
                 s21_sprintf(c2, "%10d %-10d %4.10d", 1, 666, 2544325));
ck_assert_str_eq(c1, c2);
ck_assert_int_eq(sprintf(c1, "%+4.10d", 1), s21_sprintf(c2, "%+4.10d", 1));
ck_assert_str_eq(c1, c2);
ck_assert_int_eq(sprintf(c1, "%+20.10d", 1), s21_sprintf(c2, "%+20.10d", 1));
ck_assert_str_eq(c1, c2);
ck_assert_int_eq(sprintf(c1, "%-20.10d", 1), s21_sprintf(c2, "%-20.10d", 1));
ck_assert_str_eq(c1, c2);
ck_assert_int_eq(sprintf(c1, "%+-20.10d", 1), s21_sprintf(c2, "%+-20.10d", 1));
ck_assert_str_eq(c1, c2);
ck_assert_int_eq(sprintf(c1, "%-+10d", 666), s21_sprintf(c2, "%-+10d", 666));
ck_assert_str_eq(c1, c2);
ck_assert_int_eq(sprintf(c1, "%% % d", 1), s21_sprintf(c2, "%% % d", 1));
ck_assert_str_eq(c1, c2);
ck_assert_int_eq(sprintf(c1, "%10d", -2147483647),
                 s21_sprintf(c2, "%10d", -2147483647));
ck_assert_str_eq(c1, c2);
ck_assert_int_eq(sprintf(c1, "%10ld", -21474836488),
                 s21_sprintf(c2, "%10ld", -21474836488));
ck_assert_str_eq(c1, c2);
ck_assert_int_eq(sprintf(c1, "%10hd", 55643), s21_sprintf(c2, "%10hd", 55643));
ck_assert_str_eq(c1, c2);

}
END_TEST

START_TEST(test_s21_sprintf_u)
{
char str1[1000];
char str2[1000];
unsigned short h = 115;
unsigned long l = 123325242342l;
int r1 =
    sprintf(str1, "%u%15u%-20u%10u%-15.10u!%20.2u!%.u%.10u%-20.12lu%19hu",
            4321u, -34567, 2342u, 12346u, 234542u, 234523u, 2345u, 2432u, l, h);
int r2 = s21_sprintf(
    str2, "%u%15u%-20u%10u%-15.10u!%20.2u!%.u%.10u%-20.12lu%19hu", 4321u,
    -34567, 2342u, 12346u, 234542u, 234523u, 2345u, 2432u, l, h);
ck_assert_str_eq(str1, str2);
ck_assert_int_eq(r1, r2);

}
END_TEST

START_TEST(test_s21_sprintf_f)
{
char c1[100] = "a";
char c2[100] = "a";
char c3[100] = "lolkek";
char c4[100] = "lolkek";
ck_assert_int_eq(sprintf(c1, "test %f %f %f", 5.1, 0.1, -0.00001),
                 s21_sprintf(c2, "test %f %f %f", 5.1, 0.1, -0.00001));
ck_assert_str_eq(c1, c2);
ck_assert_int_eq(sprintf(c3 + 6, "%f", -6000.00006),
                 s21_sprintf(c4 + 6, "%f", -6000.00006));
ck_assert_str_eq(c3, c4);
ck_assert_int_eq(sprintf(c3, "%flolkek%f", -6000.00006, -1.0),
                 s21_sprintf(c4, "%flolkek%f", -6000.00006, -1.0));
ck_assert_str_eq(c3, c4);
ck_assert_int_eq(sprintf(c3, "%.0f", 99.99), s21_sprintf(c4, "%.0f", 99.99));
printf("%s\n", c4);
ck_assert_str_eq(c3, c4);

// imported
}
END_TEST

START_TEST(test_s21_sprintf_f2)
{
char str1[1000];
char str2[1000];
int r1 =
    sprintf(str1, "%+-10.5f%+10.2f%15.16f%+.10f%.16f%-10.f%25.f%25.f%.2f%.f",
            2546.4324, 3452.4325, 5678.43256, 456789.243242, 3456789123.43245,
            12345.6788, 34.4325432, 4325678.43242, 99.990, 34567.43244);
int r2 = s21_sprintf(
    str2, "%+-10.5f%+10.2f%15.16f%+.10f%.16f%-10.f%25.f%25.f%.2f%.f", 2546.4324,
    3452.4325, 5678.43256, 456789.243242, 3456789123.43245, 12345.6788,
    34.4325432, 4325678.43242, 99.990, 34567.43244);
ck_assert_str_eq(str1, str2);
ck_assert_int_eq(r1, r2);

}
END_TEST

START_TEST(test_s21_sprintf_c)
{
char c1[100] = "a";
char c2[100] = "a";
ck_assert_int_eq(sprintf(c1, "test %c%c%lc", 'a', 'c', 'c'),
                 s21_sprintf(c2, "test %c%c%c", 'a', 'c', 'c'));
ck_assert_str_eq(c1, c2);
ck_assert_int_eq(sprintf(c1, "%lc", L'a'), s21_sprintf(c2, "%lc", L'a'));
ck_assert_str_eq(c1, c2);

// %c imported
char str1[1000];
char str2[1000];
int r1 = sprintf(str1, "%c%c%c%c%c%c%c%c%c%c", 'a', 'e', 'f', 'R', 'Q', 10, 'P',
                 'L', 20, 'x');
int r2 = s21_sprintf(str2, "%c%c%c%c%c%c%c%c%c%c", 'a', 'e', 'f', 'R', 'Q', 10,
                     'P', 'L', 20, 'x');
ck_assert_str_eq(str1, str2);
ck_assert_int_eq(r1, r2);

}
END_TEST

START_TEST(test_s21_sprintf_s)
{
char str1[1000];
char str2[1000];
char s[10] = {'h', 'e', 'l', 'l', 'o'};
int r1 = sprintf(str1, "%ls%10ls%.0ls%7.2ls%-10.3ls %5.3s%-5.0s%s%s%6.33s",
                 L"aboba", L"helloworld", L"ABOBA", L"ABOBBAAA", L"AAABOBA",
                 "QWERTY", "AAAAABOOOOOBAAA", "ABOBAAAAA", s, s);
int r2 = s21_sprintf(str2, "%ls%10ls%.0ls%7.2ls%-10.3ls %5.3s%-5.0s%s%s%6.33s",
                     L"aboba", L"helloworld", L"ABOBA", L"ABOBBAAA", L"AAABOBA",
                     "QWERTY", "AAAAABOOOOOBAAA", "ABOBAAAAA", s, s);
ck_assert_str_eq(str1, str2);
ck_assert_int_eq(r1, r2);

}
END_TEST

START_TEST(test_s21_sprintf_percent)
{
char str1[1000];
char str2[1000];
int r1 = sprintf(str1, "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%");
int r2 = s21_sprintf(str2, "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%");
ck_assert_str_eq(str1, str2);
ck_assert_int_eq(r1, r2);



}
END_TEST

START_TEST(s21_sprintf_f_test)
{
  char str[80] = {'\0'};
  char str_orig[80] = {'\0'};

  double b_1 = -1.0234;
  int res_1 = s21_sprintf(str, "% 5.1f", b_1);
  int res_1_orig = sprintf(str_orig, "% 5.1f", b_1);
  ck_assert_int_eq(res_1, res_1_orig);
  ck_assert_str_eq(str, str_orig);

  double b_2 = 0.02345;
  int res_2 = s21_sprintf(str, "%+-5.3f", b_2);
  int res_2_orig = sprintf(str_orig, "%+-5.3f", b_2);
  ck_assert_int_eq(res_2, res_2_orig);
  ck_assert_str_eq(str, str_orig);

  double b_3 = 13.04;
  int res_3 = s21_sprintf(str, "%15.5f", b_3);
  int res_3_orig = sprintf(str_orig, "%15.5f", b_3);
  ;
  ck_assert_int_eq(res_3, res_3_orig);
  ck_assert_str_eq(str, str_orig);

  double b_4 = 5.6;
  int res_4 = s21_sprintf(str, "%+3.5f", b_4);
  int res_4_orig = sprintf(str_orig, "%+3.5f", b_4);
  ck_assert_int_eq(res_4, res_4_orig);
  ck_assert_str_eq(str, str_orig);

  double b_5 = 9.6;
  int res_5 = s21_sprintf(str, "%-3.5f", b_5);
  int res_5_orig = sprintf(str_orig, "%-3.5f", b_5);
  ck_assert_int_eq(res_5, res_5_orig);
  ck_assert_str_eq(str, str_orig);


}
END_TEST

START_TEST(s21_sprintf_d_test)
{
  char str[80] = {'\0'};
  char str_orig[80] = {'\0'};
  int d = 228;

  int res_1 = s21_sprintf(str, "%10.5d", d);
  int res_1_orig = sprintf(str_orig, "%10.5d", d);
  ck_assert_int_eq(res_1, res_1_orig);
  ck_assert_str_eq(str, str_orig);

  int res_2 = s21_sprintf(str, "% 10.5d", d);
  int res_2_orig = sprintf(str_orig, "% 10.5d", d);
  ck_assert_int_eq(res_2, res_2_orig);
  ck_assert_str_eq(str, str_orig);

  int res_3 = s21_sprintf(str, "%3.5d", d);
  int res_3_orig = sprintf(str_orig, "%3.5d", d);
  ck_assert_int_eq(res_3, res_3_orig);
  ck_assert_str_eq(str, str_orig);

  int res_4 = s21_sprintf(str, "%d", d);
  int res_4_orig = sprintf(str_orig, "%d", d);
  ck_assert_int_eq(res_4, res_4_orig);
  ck_assert_str_eq(str, str_orig);

  int res_5 = s21_sprintf(str, "%0d", d);
  int res_5_orig = sprintf(str_orig, "%0d", d);
  ck_assert_int_eq(res_5, res_5_orig);
  ck_assert_str_eq(str, str_orig);

  int res_6 = s21_sprintf(str, "%-d", d);
  int res_6_orig = sprintf(str_orig, "%-d", d);
  ck_assert_int_eq(res_6, res_6_orig);
  ck_assert_str_eq(str, str_orig);

  int res_7 = s21_sprintf(str, "%+d", d);
  int res_7_orig = sprintf(str_orig, "%+d", d);
  ck_assert_int_eq(res_7, res_7_orig);
  ck_assert_str_eq(str, str_orig);

  int res_8 = s21_sprintf(str, "% d", d);
  int res_8_orig = sprintf(str_orig, "% d", d);
  ck_assert_int_eq(res_8, res_8_orig);
  ck_assert_str_eq(str, str_orig);

  int res_9 = s21_sprintf(str, "%5d", d);
  int res_9_orig = sprintf(str_orig, "%5d", d);
  ck_assert_int_eq(res_9, res_9_orig);
  ck_assert_str_eq(str, str_orig);

  int res_10 = s21_sprintf(str, "%-5d", d);
  int res_10_orig = sprintf(str_orig, "%-5d", d);
  ck_assert_int_eq(res_10, res_10_orig);
  ck_assert_str_eq(str, str_orig);

  int res_11 = s21_sprintf(str, "%+5d", d);
  int res_11_orig = sprintf(str_orig, "%+5d", d);
  ck_assert_int_eq(res_11, res_11_orig);
  ck_assert_str_eq(str, str_orig);

  int res_12 = s21_sprintf(str, "% 5d", d);
  int res_12_orig = sprintf(str_orig, "% 5d", d);
  ck_assert_int_eq(res_12, res_12_orig);
  ck_assert_str_eq(str, str_orig);

  int res_13 = s21_sprintf(str, "%.5d", d);
  int res_13_orig = sprintf(str_orig, "%.5d", d);
  ck_assert_int_eq(res_13, res_13_orig);
  ck_assert_str_eq(str, str_orig);



}
END_TEST

START_TEST(s21_sprintf_c_test)
{
  char str[80] = {'\0'};
  char str_orig[80] = {'\0'};
  char A = 'A';

  int res_1 = s21_sprintf(str, "%c", A);
  int res_1_orig = sprintf(str_orig, "%c", A);
  ck_assert_int_eq(res_1, res_1_orig);
  ck_assert_str_eq(str, str_orig);

  int res_2 = s21_sprintf(str, "%-c", A);
  int res_2_orig = sprintf(str_orig, "%-c", A);
  ck_assert_int_eq(res_2, res_2_orig);
  ck_assert_str_eq(str, str_orig);

  int res_4 = s21_sprintf(str, "%10c", A);
  int res_4_orig = sprintf(str_orig, "%10c", A);
  ck_assert_int_eq(res_4, res_4_orig);
  ck_assert_str_eq(str, str_orig);

  int res_5 = s21_sprintf(str, "%-2c", A);
  int res_5_orig = sprintf(str_orig, "%-2c", A);
  ck_assert_int_eq(res_5, res_5_orig);
  ck_assert_str_eq(str, str_orig);


}
END_TEST

START_TEST(s21_sprintf_s_test)
{
  char str[80] = {'\0'};
  char str_orig[80] = {'\0'};
  char *A = "Ochko";

  int res_1 = s21_sprintf(str, "%s", A);
  int res_1_orig = sprintf(str_orig, "%s", A);
  ck_assert_int_eq(res_1, res_1_orig);
  ck_assert_str_eq(str, str_orig);

  int res_2 = s21_sprintf(str, "%-s", A);
  int res_2_orig = sprintf(str_orig, "%-s", A);
  ck_assert_int_eq(res_2, res_2_orig);
  ck_assert_str_eq(str, str_orig);

  int res_4 = s21_sprintf(str, "%10s", A);
  int res_4_orig = sprintf(str_orig, "%10s", A);
  ck_assert_int_eq(res_4, res_4_orig);
  ck_assert_str_eq(str, str_orig);

  int res_5 = s21_sprintf(str, "%.5s", A);
  int res_5_orig = sprintf(str_orig, "%.5s", A);
  ck_assert_int_eq(res_5, res_5_orig);
  ck_assert_str_eq(str, str_orig);

  int res_6 = s21_sprintf(str, "%-10s", A);
  int res_6_orig = sprintf(str_orig, "%-10s", A);
  ck_assert_int_eq(res_6, res_6_orig);
  ck_assert_str_eq(str, str_orig);


}
END_TEST

START_TEST(s21_sprintf_ld_test)
{
  char str[80] = {'\0'};
  char str_orig[80] = {'\0'};
  long int d = 1504389565748;

  int res_1 = s21_sprintf(str, "%10.5ld", d);
  int res_1_orig = sprintf(str_orig, "%10.5ld", d);
  ck_assert_int_eq(res_1, res_1_orig);
  ck_assert_str_eq(str, str_orig);

  int res_2 = s21_sprintf(str, "% 10.5ld", d);
  int res_2_orig = sprintf(str_orig, "% 10.5ld", d);
  ck_assert_int_eq(res_2, res_2_orig);
  ck_assert_str_eq(str, str_orig);

  int res_3 = s21_sprintf(str, "%3.5ld", d);
  int res_3_orig = sprintf(str_orig, "%3.5ld", d);
  ck_assert_int_eq(res_3, res_3_orig);
  ck_assert_str_eq(str, str_orig);

  int res_4 = s21_sprintf(str, "%ld", d);
  int res_4_orig = sprintf(str_orig, "%ld", d);
  ck_assert_int_eq(res_4, res_4_orig);
  ck_assert_str_eq(str, str_orig);

  int res_6 = s21_sprintf(str, "%-ld", d);
  int res_6_orig = sprintf(str_orig, "%-ld", d);
  ck_assert_int_eq(res_6, res_6_orig);
  ck_assert_str_eq(str, str_orig);

  int res_7 = s21_sprintf(str, "%+ld", d);
  int res_7_orig = sprintf(str_orig, "%+ld", d);
  ck_assert_int_eq(res_7, res_7_orig);
  ck_assert_str_eq(str, str_orig);

  int res_8 = s21_sprintf(str, "% ld", d);
  int res_8_orig = sprintf(str_orig, "% ld", d);
  ck_assert_int_eq(res_8, res_8_orig);
  ck_assert_str_eq(str, str_orig);

  int res_9 = s21_sprintf(str, "%5ld", d);
  int res_9_orig = sprintf(str_orig, "%5ld", d);
  ck_assert_int_eq(res_9, res_9_orig);
  ck_assert_str_eq(str, str_orig);

  int res_10 = s21_sprintf(str, "%-5ld", d);
  int res_10_orig = sprintf(str_orig, "%-5ld", d);
  ck_assert_int_eq(res_10, res_10_orig);
  ck_assert_str_eq(str, str_orig);

  int res_11 = s21_sprintf(str, "%+5ld", d);
  int res_11_orig = sprintf(str_orig, "%+5ld", d);
  ck_assert_int_eq(res_11, res_11_orig);
  ck_assert_str_eq(str, str_orig);

  int res_12 = s21_sprintf(str, "% 5ld", d);
  int res_12_orig = sprintf(str_orig, "% 5ld", d);
  ck_assert_int_eq(res_12, res_12_orig);
  ck_assert_str_eq(str, str_orig);

  int res_13 = s21_sprintf(str, "%.5ld", d);
  int res_13_orig = sprintf(str_orig, "%.5ld", d);
  ck_assert_int_eq(res_13, res_13_orig);
  ck_assert_str_eq(str, str_orig);


}
END_TEST

START_TEST(s21_sprintf_u_test)
{
  char str[80] = {'\0'};
  char str_orig[80] = {'\0'};
  unsigned int u = 228;

  int res_1 = s21_sprintf(str, "%10.5u", u);
  int res_1_orig = sprintf(str_orig, "%10.5u", u);
  ck_assert_int_eq(res_1, res_1_orig);
  ck_assert_str_eq(str, str_orig);

  int res_2 = s21_sprintf(str, "%-10.5u", u);
  int res_2_orig = sprintf(str_orig, "%-10.5u", u);
  ck_assert_int_eq(res_2, res_2_orig);
  ck_assert_str_eq(str, str_orig);

  int res_3 = s21_sprintf(str, "%3.5u", u);
  int res_3_orig = sprintf(str_orig, "%3.5u", u);
  ck_assert_int_eq(res_3, res_3_orig);
  ck_assert_str_eq(str, str_orig);

  int res_4 = s21_sprintf(str, "%u", u);
  int res_4_orig = sprintf(str_orig, "%u", u);
  ck_assert_int_eq(res_4, res_4_orig);
  ck_assert_str_eq(str, str_orig);

  int res_6 = s21_sprintf(str, "%u", u);
  int res_6_orig = sprintf(str_orig, "%u", u);
  ck_assert_int_eq(res_6, res_6_orig);
  ck_assert_str_eq(str, str_orig);

  int res_9 = s21_sprintf(str, "%5u", u);
  int res_9_orig = sprintf(str_orig, "%5u", u);
  ck_assert_int_eq(res_9, res_9_orig);
  ck_assert_str_eq(str, str_orig);

  int res_10 = s21_sprintf(str, "%-5u", u);
  int res_10_orig = sprintf(str_orig, "%-5u", u);
  ck_assert_int_eq(res_10, res_10_orig);
  ck_assert_str_eq(str, str_orig);

  int res_12 = s21_sprintf(str, "%10.5u", u);
  int res_12_orig = sprintf(str_orig, "%10.5u", u);
  ck_assert_int_eq(res_12, res_12_orig);
  ck_assert_str_eq(str, str_orig);

  int res_13 = s21_sprintf(str, "%.5u", u);
  int res_13_orig = sprintf(str_orig, "%.5u", u);
  ck_assert_int_eq(res_13, res_13_orig);
  ck_assert_str_eq(str, str_orig);








/////////////// new tests_sprintf

}
END_TEST

START_TEST(d_specifier_testing)
{
  char result[400];
  char result2[400];
  char result3[400];
  char result4[400];
  char format[] =
      "print: %d %hd %ld, %+d %+d % d %05d %05d %-5d %5d %.6d %1d %05d";
  int printCount = sprintf(result, format, __INT_MAX__, __SHRT_MAX__,
                           __LONG_MAX__, 2, 2, 2, 23, 23, 23, 23, 20, 1, 232);
  int printCount2 =
      s21_sprintf(result2, format, __INT_MAX__, __SHRT_MAX__, __LONG_MAX__, 2,
                  2, 2, 23, 23, 23, 23, 20, 1, 232);
  int printCount3 =
      sprintf(result3, format, -__INT_MAX__, -__SHRT_MAX__, -__LONG_MAX__, -2,
              -2, -2, -23, -23, -23, -23, -20, -1, -232);
  int printCount4 =
      s21_sprintf(result4, format, -__INT_MAX__, -__SHRT_MAX__, -__LONG_MAX__,
                  -2, -2, -2, -23, -23, -23, -23, -20, -1, -232);
  ck_assert_str_eq(result, result2);
  ck_assert_str_eq(result3, result4);
  ck_assert_int_eq(printCount, printCount2);
  ck_assert_int_eq(printCount3, printCount4);


}
END_TEST

START_TEST(u_specifier_testing)
{
  char result[400];
  char result2[400];
  char format[] =
      "print: %u %hu %lu, %u %u %u %05u %05u %-5u %5u %.6u %05u";
  int printCount = sprintf(result, format, __INT16_MAX__, __INT32_MAX__,
                           __INT64_MAX__, 2, 2, 2, 23, 23, 23, 23, 20, 232);
  int printCount2 =
      s21_sprintf(result2, format, __INT16_MAX__, __INT32_MAX__, __INT64_MAX__,
                  2, 2, 2, 23, 23, 23, 23, 20, 232);
  ck_assert_str_eq(result, result2);
  ck_assert_int_eq(printCount, printCount2);


}
END_TEST

START_TEST(x_specifier_testing)
{
  char result[400];
  char result2[400];
  char format[] =
      "print: %x %hx %lx, %x %x %x %05x %05x %-5x %5x %.6x %#x %05x";
  int printCount =
      sprintf(result, format, __INT16_MAX__, __INT32_MAX__, __INT64_MAX__, 2, 2,
              2, 23, 23, 23, 23, 20, 222, 232);
  int printCount2 =
      s21_sprintf(result2, format, __INT16_MAX__, __INT32_MAX__, __INT64_MAX__,
                  2, 2, 2, 23, 23, 23, 23, 20, 222, 232);
  ck_assert_str_eq(result, result2);
  ck_assert_int_eq(printCount, printCount2);

}
END_TEST

START_TEST(X_specifier_testing)
{
  char result[400];
  char result2[400];
  char format[] =
      "print: %X %hX %lX, %X %X %X %05X %05X %-5X %5X %.6X %#X %05X";
  int printCount =
      sprintf(result, format, __INT16_MAX__, __INT32_MAX__, __INT64_MAX__, 2, 2,
              2, 23, 23, 23, 23, 20, 2222, 232);
  int printCount2 =
      s21_sprintf(result2, format, __INT16_MAX__, __INT32_MAX__, __INT64_MAX__,
                  2, 2, 2, 23, 23, 23, 23, 20, 2222, 232);
  ck_assert_str_eq(result, result2);
  ck_assert_int_eq(printCount, printCount2);


}
END_TEST

START_TEST(o_specifier_testing)
{
  char result[400];
  char result2[400];
  char format[] =
      "print: %o %ho, %o %o %o %05o %05o %-5o %5o %.6o %#o %05o";
  int printCount =
      sprintf(result, format, __INT16_MAX__, __INT32_MAX__, 2, 2,
              2, 23, 23, 23, 23, 20, 222, 232);
  int printCount2 =
      s21_sprintf(result2, format, __INT16_MAX__, __INT32_MAX__, 2, 2,
              2, 23, 23, 23, 23, 20, 222, 232);
  ck_assert_str_eq(result, result2);
  ck_assert_int_eq(printCount, printCount2);


}
END_TEST

START_TEST(percent_specifier_testing)
{
  char result[400];
  char result2[400];
  char format[] = "print: %% %#% %-020.10% %.10l% %10h% % #L% %d %05%";
  int printCount = sprintf(result, format, 232);
  int printCount2 = s21_sprintf(result2, format, 232);
  ck_assert_str_eq(result, result2);
  ck_assert_int_eq(printCount, printCount2);


}
END_TEST

START_TEST(f_specifier_testing)
{
  char result[400];
  char result2[400];
  char format[] =
      "print: %.*f %5f %-5f %0f % f %+f %#f %.1f %.10f %.13f %#.0f %lf %f lol";
  int printCount =
      sprintf(result, format, 4, 50.91, 50.214, 50.87, 50.878787, 50.87687,
              50.7777, 50.4655, 50.87769, 50.65554, 50.6558, 50.866427659,
              100000000000.76443553, 50.75475465);
  int printCount2 =
      s21_sprintf(result2, format, 4, 50.91, 50.214, 50.87, 50.878787, 50.87687,
                  50.7777, 50.4655, 50.87769, 50.65554, 50.6558, 50.866427659,
                  100000000000.76443553, 50.75475465);
  char result3[400];
  char result4[400];
  int printCount3 =
      sprintf(result3, format, 4, -50.91, -50.214, -50.87, -50.878787,
              -50.87687, -50.7777, -50.4655, -50.87769, -50.65554, -50.6558,
              -50.866427659, -100000000000.76443553, -50.75475465);
  int printCount4 =
      s21_sprintf(result4, format, 4, -50.91, -50.214, -50.87, -50.878787,
                  -50.87687, -50.7777, -50.4655, -50.87769, -50.65554, -50.6558,
                  -50.866427659, -100000000000.76443553, -50.75475465);
  ck_assert_str_eq(result, result2);
  ck_assert_str_eq(result3, result4);
  ck_assert_int_eq(printCount, printCount2);
  ck_assert_int_eq(printCount3, printCount4);


}
END_TEST

START_TEST(p_specifier_testing)
{
  char result[400];
  char result2[400];
  char format[] = "print: %p %p %5p %-5p %p %p %5p %p";
  int printCount = sprintf(result, format, result, result, result, result,
                           result, result, result, result);
  int printCount2 = s21_sprintf(result2, format, result, result, result, result,
                                result, result, result, result);
  ck_assert_str_eq(result, result2);
  ck_assert_int_eq(printCount, printCount2);


}
END_TEST

START_TEST(e_specifier_testing)
{
  char result[400];
  char result2[400];
  char format[] =
      "print: %.*e %5e %-5e %0e % e %+e %#e %.1e %.10e %.15e %#e %le %e lol";
  int printCount =
      sprintf(result, format, 4, 50.91, 50.214, 50.87, 50.878787, 50.87687,
              50.7777, 50.4655, 50.87769, 50.65554, 50.6558, 50.866427659,
              100000000000.76443553, 50.75475465);
  int printCount2 =
      s21_sprintf(result2, format, 4, 50.91, 50.214, 50.87, 50.878787, 50.87687,
                  50.7777, 50.4655, 50.87769, 50.65554, 50.6558, 50.866427659,
                  100000000000.76443553, 50.75475465);
  ck_assert_str_eq(result, result2);
  ck_assert_int_eq(printCount, printCount2);


}
END_TEST

START_TEST(E_specifier_testing)
{
  char result[400];
  char result2[400];
  char format[] =
      "print: %.*E %5E %-5E %0E % E %+E %#E %.1E %.10E %.15E %#E %lE %E lol";
  int printCount =
      sprintf(result, format, 4, 50.91, 50.214, 50.87, 50.878787, 50.87687,
              50.7777, 50.4655, 50.87769, 50.65554, 50.6558, 50.866427659,
              13214413214.76443553, 50.75475465);
  int printCount2 =
      s21_sprintf(result2, format, 4, 50.91, 50.214, 50.87, 50.878787, 50.87687,
                  50.7777, 50.4655, 50.87769, 50.65554, 50.6558, 50.866427659,
                  13214413214.76443553, 50.75475465);
  ck_assert_str_eq(result, result2);
  ck_assert_int_eq(printCount, printCount2);


}
END_TEST

START_TEST(g_specifier_testing)
{
  char result[400];
  char result2[400];
  char format[] =
      "print: %.*g %5g %-5g %0g % g %+g %#g %.1g %.10g %.9g %#g %lg %g lol";
  int printCount =
      sprintf(result, format, 4, 50.91, 50.214, 50.87, 50.878787, 50.87687,
              50.7777, 50.4655, 50.87769, 50.65554, 50.6558, 50.866427659,
              13214413214.76443553, 50.75474465);
  int printCount2 =
      s21_sprintf(result2, format, 4, 50.91, 50.214, 50.87, 50.878787, 50.87687,
                  50.7777, 50.4655, 50.87769, 50.65554, 50.6558, 50.866427659,
                  13214413214.76443553, 50.75475465);
  ck_assert_str_eq(result, result2);
  ck_assert_int_eq(printCount, printCount2);


}
END_TEST

START_TEST(G_specifier_testing)
{
  char result[400];
  char result2[400];
  char format[] =
      "print: %.*G %5G %-5G %0G %G %+G %#G %.1G %.10G %.9G %#G %lG %G lol";
  int printCount =
      sprintf(result, format, 4, 50.91, 50.214, 50.87, 50.878787, 50.87687,
              50.7777, 50.4655, 50.87769, 50.65554, 50.6558, 50.866427659,
              13214413214.76443553, 50.75474465);
  int printCount2 =
      s21_sprintf(result2, format, 4, 50.91, 50.214, 50.87, 50.878787, 50.87687,
                  50.7777, 50.4655, 50.87769, 50.65554, 50.6558, 50.866427659,
                  13214413214.76443553, 50.75475465);
  ck_assert_str_eq(result, result2);
  ck_assert_int_eq(printCount, printCount2);




}
END_TEST

START_TEST(n_specifier_testing)
{
  char str1[50];
  char str2[50];
  int ret = 0;
  char *format = "How many chars written before n %n";
  s21_sprintf(str1, format, &ret);
  sprintf(str2, format, &ret);

  ck_assert_str_eq(str1, str2);


}
END_TEST

START_TEST(n_specifier_testing_2)
{
  char str1[50];
  char str2[50];
  int n1;
  int n2;
  s21_sprintf(str1, "%d%n", 123, &n1);
  sprintf(str2, "%d%n", 123, &n2);
  ck_assert_str_eq(str1, str2);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, test_s21_strerror);
    tcase_add_test(tc1_1, test_s21_strlen);
    tcase_add_test(tc1_1, test_s21_strpbrk);
    tcase_add_test(tc1_1, test_s21_strrchr);
    tcase_add_test(tc1_1, test_s21_strstr);
    tcase_add_test(tc1_1, test_s21_strtok_1);
    tcase_add_test(tc1_1, test_s21_strtok_2);
    tcase_add_test(tc1_1, test_s21_memchr);
    tcase_add_test(tc1_1, test_s21_memcmp);
    tcase_add_test(tc1_1, s21_memcmp_different_string_but_same_comparable_bytes);
    tcase_add_test(tc1_1, s21_memcmp_first_string_bigger);
    tcase_add_test(tc1_1, s21_memcmp_second_string_bigger);
    tcase_add_test(tc1_1, s21_memcmp_empty_strings);
    tcase_add_test(tc1_1, s21_memcmp_different_string_compare_null_bytes);
    tcase_add_test(tc1_1, S21_MEMCPY);
    tcase_add_test(tc1_1, S21_MEMSET);
    tcase_add_test(tc1_1, S21_STRNCAT);
    tcase_add_test(tc1_1, S21_STRCHR);
    tcase_add_test(tc1_1, S21_STRNCMP);
    tcase_add_test(tc1_1, S21_STRNCPY);
    tcase_add_test(tc1_1, S21_STRCSPN);
    tcase_add_test(tc1_1, test_s21_sprintf_d);
    tcase_add_test(tc1_1, test_s21_sprintf_u);
    tcase_add_test(tc1_1, test_s21_sprintf_f);
    tcase_add_test(tc1_1, test_s21_sprintf_f2);
    tcase_add_test(tc1_1, test_s21_sprintf_c);
    tcase_add_test(tc1_1, test_s21_sprintf_s);
    tcase_add_test(tc1_1, test_s21_sprintf_percent);
    tcase_add_test(tc1_1, s21_sprintf_f_test);
    tcase_add_test(tc1_1, s21_sprintf_d_test);
    tcase_add_test(tc1_1, s21_sprintf_c_test);
    tcase_add_test(tc1_1, s21_sprintf_s_test);
    tcase_add_test(tc1_1, s21_sprintf_ld_test);
    tcase_add_test(tc1_1, s21_sprintf_u_test);
    tcase_add_test(tc1_1, d_specifier_testing);
    tcase_add_test(tc1_1, u_specifier_testing);
    tcase_add_test(tc1_1, x_specifier_testing);
    tcase_add_test(tc1_1, X_specifier_testing);
    tcase_add_test(tc1_1, o_specifier_testing);
    tcase_add_test(tc1_1, percent_specifier_testing);
    tcase_add_test(tc1_1, f_specifier_testing);
    tcase_add_test(tc1_1, p_specifier_testing);
    tcase_add_test(tc1_1, e_specifier_testing);
    tcase_add_test(tc1_1, E_specifier_testing);
    tcase_add_test(tc1_1, g_specifier_testing);
    tcase_add_test(tc1_1, G_specifier_testing);
    tcase_add_test(tc1_1, n_specifier_testing);
    tcase_add_test(tc1_1, n_specifier_testing_2);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
